// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzEpgswKKiqO88BEuNTKg9_GI0uOjq_zQ',
    appId: '1:156971063806:web:6eee297983d888bf2588af',
    messagingSenderId: '156971063806',
    projectId: 'eballot-e044d',
    authDomain: 'eballot-e044d.firebaseapp.com',
    storageBucket: 'eballot-e044d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMYcEJfda4-bP6iYjacB4G5cHJtRSQCdU',
    appId: '1:156971063806:android:d481947174f509752588af',
    messagingSenderId: '156971063806',
    projectId: 'eballot-e044d',
    storageBucket: 'eballot-e044d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGEkcVC33oiqA4tEgKXREL10A5G-mGLeo',
    appId: '1:156971063806:ios:9f9f2cd924813b4c2588af',
    messagingSenderId: '156971063806',
    projectId: 'eballot-e044d',
    storageBucket: 'eballot-e044d.firebasestorage.app',
    iosBundleId: 'com.example.eballot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGEkcVC33oiqA4tEgKXREL10A5G-mGLeo',
    appId: '1:156971063806:ios:9f9f2cd924813b4c2588af',
    messagingSenderId: '156971063806',
    projectId: 'eballot-e044d',
    storageBucket: 'eballot-e044d.firebasestorage.app',
    iosBundleId: 'com.example.eballot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzEpgswKKiqO88BEuNTKg9_GI0uOjq_zQ',
    appId: '1:156971063806:web:58b0d6b7897a8a7e2588af',
    messagingSenderId: '156971063806',
    projectId: 'eballot-e044d',
    authDomain: 'eballot-e044d.firebaseapp.com',
    storageBucket: 'eballot-e044d.firebasestorage.app',
  );
}
